### ISSUE TITLE
Improve speed of generate_index_dates

### ISSUE THREAD

**Issue by kurttaylor** [opensafely/post-covid-diabetes#20]
Currently, the new generate_index_dates action is extremely slow to run on dummy data for anything N > 20,000. I am conscious how long this action could take to run on real data. Potentially worth trying to rewrite this script using data.table to see if it speeds things up?

**Comment by venexia** [comment]
There is a [data table back-end for dplyr](https://dtplyr.tidyverse.org/) if you don't want to do a full rewrite?

**Comment by venexia** [comment]
To clarify, I am happy for stuff to be written in data.table but I know many of our team members are big tidyverse fans!

**Comment by kurttaylor** [comment]
@venexia the script runs locally in RStudio in a matter of seconds. Do you know of any reasons why it could be taking so long when executing the script via OpenSAFELY?

**Comment by kurttaylor** [comment]
Issue addressed [in this PR](https://github.com/opensafely/post-covid-gastrointestinal/pull/10) in the GI repo. Changes to be ported over.
