### ISSUE TITLE
sample size in new study definitions

### ISSUE THREAD

**Issue by kurttaylor** [opensafely/post-covid-diabetes#21]
The dataset N’s (input feather files) that are generated by the new study def’s are:
prevax - ~23 million
vax - ~21 million
unvax - ~21 million
I am wondering where/why we losing the ~2million
 
These N's can be seen in the log files of the preprocess script in Level 4 (post-covid-diabetes-new-study-def-test)

**Comment by kurttaylor** [comment]
@marwaalarab @venexia please see the preprocess log files in level 4 located in "workspaces/post-covid-diabetes-new-study-def-test/metadata/preprocess_data_*.txt" 
These log files show a summary of all the dates in index dates and the N's of the input files created by the study definitions. I still can't see anything obvious to explain where/why the delta era populations are different. Let me know what you think

**Comment by marwaalarab** [comment]
@kurttaylor are these N before applying preprocessing or after

**Comment by kurttaylor** [comment]
Before. The N's above are from the input.feather files immediately as they are read into the preprocessing script (before any preprocessing is done). Do you have access to L4?
